xs<-c("ab","c","def","gh")
l<-list()
cs=c()
for(i in 1:length(xs)) 
    if(i%%2==0) {
        print(xs[i])
        l<-append(l,xs[i])
        cs=c(cs,xs[i])
    }
print(l)
print(cs)
paste(l,sep="",collapse="\n")
paste(cs,sep="",collapse="\n")
#text<-paste(l,sep="",collapse="\n")
writeLines(cs, con = stdout(), sep = "\n", useBytes = FALSE)
